### ISSUE TITLE
Добавить тесты

### ISSUE THREAD

**Issue by Cosebdd** [atyrin/veeamchan#15]
Может добавить тестовый набор данных через POST, чтобы не набивать вручную всяикй раз?

**Comment by atyrin** [comment]
Как-то пока не вижу больших профитов в этом.

И где тесты будут отрабатывать? Если их должен запускать вручную девелопер, то надо в репозитории все это хранить. Если автоматически, то нужна еще машина, которая на каждый пуллреквест будет все это загружать себе и гонять.
