### ISSUE TITLE
Добавить возможность модерации

### ISSUE THREAD

**Issue by Cosebdd** [atyrin/veeamchan#25]
Добавить возможность удалять треды и посты на случай использования пользователями нелегального контента.

**Comment by atyrin** [comment]
Просто питоновского файлика, который в качестве аргумента принимает номер поста достаточно наверно?
По сути же удаляя ОП пост → удаляется и тред?

**Comment by Cosebdd** [comment]
Да, у постов стоит
`thread_link = ReferenceField(Thread, reverse_delete_rule=CASCADE, required=True)`
смотреть на `reverse_delete_rule=CASCADE`

**Comment by atyrin** [comment]
#26

**Comment by atyrin** [comment]
@Cosebdd что-то еще по модерации надо, кроме удаления?

**Comment by Cosebdd** [comment]
Типа менять сообщения? Думаю, что удалению достаточно

**Comment by atyrin** [comment]
@Cosebdd красным текстом в тексте сообщения писать «НЛО удалило этот пост» или что-то в этом духе.
Вообще сомневаюсь, что это пригодится.

**Comment by atyrin** [comment]
Ну раз удаления достаточно, то вроде как все сделано. Посты и треды с зависимыми от них элементами удаляются.

Если будут дополнительно вкручены тамбнейлы и другие элементы, то надо иметь в виду, что скрипт придется дорабатывать в этом плане.

сейчас он работает в духе:
mocherator.py 12 23 24
и по очереди начнет удалять эти посты.
