### ISSUE TITLE
Подгружать фреймы после заргузки страницы

### ISSUE THREAD

**Issue by Cosebdd** [atyrin/veeamchan#30]
Фреймы ютуба, яндекс музыки и т.п. следует подгружать в последнюю очередь

**Comment by atyrin** [comment]
Осталось запилить тред с фреймами яндекс музыки, чтобы можно было посмотреть есть ли профиты.
Сейчас дергаем список фреймов после загрузки страницы и каждые 500 мс подгружаем следующий.
