### ISSUE TITLE
Добавить поле с именем файла к кнопке Browse

### ISSUE THREAD

**Issue by Cosebdd** [atyrin/veeamchan#6]
После закрытия файл диалога было бы неплохо видеть имя загружаемого файла. Также иметь возможность редактировать путь вручную

**Comment by atyrin** [comment]
Можно попробовать вот такую тему: http://markusslima.github.io/bootstrap-filestyle/

**Comment by atyrin** [comment]
@Cosebdd теперь видим имя файла. Но вот насчет необходимости редактировать путь — хз.

**Comment by Cosebdd** [comment]
@atyrin, да, я думаю поле необязательно всё же

**Comment by Cosebdd** [comment]
Короче, если всё ок, я закрою, либо ты закрой
